# Generated by Django 4.2.7 on 2023-11-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCategoriyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categories', models.CharField(blank=True, max_length=80, null=True)),
                ('icon_categories', models.ImageField(blank=True, null=True, upload_to='icon_categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_clinic', models.CharField(blank=True, max_length=250, null=True)),
                ('logo_clinic', models.ImageField(blank=True, null=True, upload_to='logo_clinic/')),
                ('about_clinic', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, max_length=10, null=True)),
                ('patients', models.IntegerField(blank=True, null=True)),
                ('experiences', models.IntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
