# Generated by Django 4.2.7 on 2023-11-27 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_clinic', '0003_clinics_id_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='id_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='find_clinic.cliniccategoriyes'),
        ),
    ]
