# Generated by Django 4.2.7 on 2023-11-27 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_clinic', '0006_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='consultation',
            name='clinic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_id', to='find_clinic.clinics'),
        ),
    ]
